### PR TITLE
move waste collection code from gitlab

### PR DESCRIPTION
**Pull request by tschlenther**
Code is merged into matsim-berlin from here:
https://gitlab.tu-berlin.de/e.ricardo/Masterarbeit/tree/berlin-scenario-merge

This is basically about the waste collection usecase, created by Ricardo Ewert, which will most probably be presented at a poster session at TRB 2020.

Please have a look at the package structure as well as the important ymls.

### CODE REVIEW

**Comment by tschlenther** [comment]
we kept the history of Ricardo Ewert's repository which seems to be based on matsi-example-project

**Comment by vsp-gleich** [comment]
some remarks after a rather superficial look on the code:
- there was an unwanted change of the gtfs2matsim version (now fixed). Besides that, it does not seem to break existing functionality.
- input files except config files should be located in public-svn and not in git (@ikaddoura : This still holds, right?)

some time in the future this should be cleaned up (e.g. by the author himself)
- do not mix English and German variable names, comments etc. -> all should be in English as the rest of this repository
- adjust hard coded file paths which only work for a certain computer, e.g. in RunAnalyse "../tubCloud/ ...."

**Comment by ikaddoura** [comment]
> input files except config files should be located in public-svn and not in git (@ikaddoura : This still holds, right?)

correct! don't upload any input files other than config files or very small test files to git!

**Comment by kainagel** [comment]
Once the files are in the branch, they are already in the git repo.

**Comment by tschlenther** [comment]
> 
> 
> input files except config files should be located in public-svn and not in git (@ikaddoura : This still holds, right?)

since this is only one and rather small shape file, @kainagel and i decided to leave it in the repo..

**Comment by tschlenther** [comment]
@kainagel all checks have passed. code clearly needs some more review/adjustments by the author. should we merge anyway or wait until the author can make further contributions?

**Pull request merged**
